services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-auth:
    build:
      context: .
      dockerfile: services/ms-auth/Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file: .env
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      - ms-auth
    restart: unless-stopped

  ms-hr:
    build:
      context: .
      dockerfile: services/ms-hr/Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
    restart: unless-stopped

  ms-production:
    build:
      context: .
      dockerfile: services/ms-production/Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
    restart: unless-stopped


volumes:
  db_data:



