spring:
  application:
    name: ms-auth
  main:
    banner-mode: "off"
  jackson:
    time-zone: Europe/Madrid
    serialization:
      indent_output: false
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: auth_user
    password: secret
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        ddl-auto: none
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

logging:
  level:
    root: WARN
    com.oscar.proyecto: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.apache.catalina: WARN

server:
  port: 8081
  address: 0.0.0.0
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

app:
  jwt:
    issuer: ms-auth
    audience: api
    private-key-location: ${APP_JWT_PRIVATE_KEY_LOCATION:classpath:jwt/private.pem}
    public-key-location: ${APP_JWT_PUBLIC_KEY_LOCATION:classpath:jwt/public.pem}
    expiration-minutes: 60
    refresh-expiration-days: ${APP_JWT_REFRESH_EXPIRATION_DAYS:7}
    max-sessions-per-user: 5
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:oscarpear99@gmail.com}}
    replyTo: ${MAIL_REPLY_TO:}

security:
  permit-all: /auth/register,/auth/login,/auth/refresh,/auth/logout,/auth/logout-all,/actuator/health,/actuator/info,/v3/api-docs/**,/swagger-ui.html,/swagger-ui/**,/auth/forgot-password,/auth/reset-password

cors:
  allowed-origins: ""
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
