spring:
  application:
    name: ms-auth
  jackson:
    time-zone: Europe/Madrid
    serialization:
      indent_output: false
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: auth_user
    password: secret
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.oscar.proyecto: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR

server:
  port: 8081
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never

app:
  jwt:
    issuer: ms-auth
    audience: api
    private-key-location: classpath:jwt/private.pem
    public-key-location: classpath:jwt/public.pem
    expiration-minutes: 60
    refresh-expiration-days: ${APP_JWT_REFRESH_EXPIRATION_DAYS:7}
    max-sessions-per-user: 5

security:
  permit-all: /auth/register,/auth/login,/auth/refresh,/auth/logout,/auth/logout-all,/actuator/health,/actuator/info,/v3/api-docs/**,/swagger-ui.html,/swagger-ui/**


cors:
  allowed-origins: ""
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
