apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  namespace: sim
  labels:
    app: ms-auth
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        eks.amazonaws.com/nodegroup: ng-public
      volumes:
        - name: jwt-keys
          secret:
            secretName: ms-auth-jwt
        - name: tmp
          emptyDir: {}
      containers:
        - name: ms-auth
          image: 039612859233.dkr.ecr.eu-west-2.amazonaws.com/ms-auth:341e1f0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ms-auth-config
            - secretRef:
                name: ms-auth-secrets
          volumeMounts:
            - name: jwt-keys
              mountPath: /run/secrets
              readOnly: true
            - name: tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: false
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
