apiVersion: v1
kind: Service
metadata:
  name: ms-auth
  namespace: sim
  labels:
    app: ms-auth
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: ms-auth
  ports:
    - name: http
      port: 80
      targetPort: 8081
